apiVersion: v1
kind: Service
metadata:
  name: jobs-service
  namespace: skill-bridge
spec:
  selector:
    app: jobs-service
  ports:
    - name: grpc
      port: 9004
      targetPort: 9004
    - name: http
      port: 8084
      targetPort: 8084
