package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"google.golang.org/grpc/status"

	authv1 "github.com/Siddsharma25/skill-bridge-platform/backend/gen/auth/v1"
	"github.com/Siddsharma25/skill-bridge-platform/backend/internal/gateway/graph/generated"
	"github.com/Siddsharma25/skill-bridge-platform/backend/internal/gateway/graph/model"
)

// Register is the resolver for the register field. It's a thin pass-through
// to auth-service over gRPC — api-gateway never touches a password hash or
// a database itself, per the gateway-is-stateless design in
// docs/DECISIONS.md.
func (r *mutationResolver) Register(ctx context.Context, email string, password string) (*model.AuthPayload, error) {
	resp, err := r.AuthClient.Register(ctx, &authv1.RegisterRequest{Email: email, Password: password})
	if err != nil {
		return nil, translateGRPCError(err)
	}
	return &model.AuthPayload{
		AccessToken: resp.GetAccessToken(),
		UserID:      resp.GetUserId(),
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*model.AuthPayload, error) {
	resp, err := r.AuthClient.Login(ctx, &authv1.LoginRequest{Email: email, Password: password})
	if err != nil {
		return nil, translateGRPCError(err)
	}
	// auth-service's Login RPC doesn't return a user_id (it only ever
	// hands back a fresh token); the client can decode the JWT's `sub`
	// claim locally if it needs the ID without a second round trip.
	return &model.AuthPayload{
		AccessToken: resp.GetAccessToken(),
	}, nil
}

// Ping is the resolver for the ping field.
func (r *queryResolver) Ping(_ context.Context) (string, error) {
	return "pong", nil
}

// translateGRPCError unwraps a gRPC status error into a plain message
// GraphQL clients can show directly, instead of gqlgen's default
// "rpc error: code = ... desc = ..." wrapping leaking transport details.
func translateGRPCError(err error) error {
	if st, ok := status.FromError(err); ok {
		return &gqlError{msg: st.Message()}
	}
	return err
}

type gqlError struct{ msg string }

func (e *gqlError) Error() string { return e.msg }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
