package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"encoding/json"
	"time"

	authv1 "github.com/Siddsharma25/skill-bridge-platform/backend/gen/auth/v1"
	jobsv1 "github.com/Siddsharma25/skill-bridge-platform/backend/gen/jobs/v1"
	skillsv1 "github.com/Siddsharma25/skill-bridge-platform/backend/gen/skills/v1"
	usersv1 "github.com/Siddsharma25/skill-bridge-platform/backend/gen/users/v1"
	"github.com/Siddsharma25/skill-bridge-platform/backend/internal/gateway/graph/generated"
	"github.com/Siddsharma25/skill-bridge-platform/backend/internal/gateway/graph/model"
	"github.com/Siddsharma25/skill-bridge-platform/backend/internal/gateway/realtime"
	"github.com/Siddsharma25/skill-bridge-platform/backend/internal/platform/rabbitmq"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// RequiredSkills is the resolver for the Job.requiredSkills field. It
// resolves every skill_id jobs-service attached to this job against
// skills-service via the per-request dataloader (see
// resolveSkillsViaLoader), which batches every id needed across every
// Job in the same `jobs`/`job` response into one GetSkillsByIds call
// instead of the Phase 1b pattern of one ListSkills call per Job — see
// docs/DECISIONS.md.
func (r *jobResolver) RequiredSkills(ctx context.Context, obj *model.Job) ([]*model.Skill, error) {
	return r.resolveSkillsViaLoader(ctx, obj.RequiredSkillIDs)
}

// Matches is the resolver for the Job.matches field (Phase 2). Thin
// pass-through to jobs-service's ListJobMatches — the matching worker's
// output, produced entirely by consuming job.posted and jobs-service's
// own user_skill_snapshot projection (see docs/DECISIONS.md). Not batched
// via a dataloader like requiredSkills: unlike skill_id resolution (which
// every Job in a list response needs, against a service with no
// single-ID lookup), matches are already a single targeted per-job gRPC
// call, so batching wouldn't remove any redundant work here.
func (r *jobResolver) Matches(ctx context.Context, obj *model.Job) ([]*model.JobMatch, error) {
	resp, err := r.JobsClient.ListJobMatches(ctx, &jobsv1.ListJobMatchesRequest{JobId: obj.ID})
	if err != nil {
		return nil, translateGRPCError(err)
	}

	ids := make([]string, len(resp.GetMatches()))
	for i, m := range resp.GetMatches() {
		ids[i] = m.GetUserId()
	}
	displayNames, err := r.resolveDisplayNamesViaLoader(ctx, ids)
	if err != nil {
		return nil, err
	}

	out := make([]*model.JobMatch, 0, len(resp.GetMatches()))
	for i, m := range resp.GetMatches() {
		out = append(out, &model.JobMatch{
			UserID:      m.GetUserId(),
			Score:       m.GetScore(),
			MatchedAt:   m.GetMatchedAt(),
			DisplayName: displayNames[i],
		})
	}
	return out, nil
}

// Register is the resolver for the register field. It's a thin pass-through
// to auth-service over gRPC — api-gateway never touches a password hash or
// a database itself, per the gateway-is-stateless design in
// docs/DECISIONS.md.
func (r *mutationResolver) Register(ctx context.Context, email string, password string) (*model.AuthPayload, error) {
	resp, err := r.AuthClient.Register(ctx, &authv1.RegisterRequest{Email: email, Password: password})
	if err != nil {
		return nil, translateGRPCError(err)
	}
	return &model.AuthPayload{
		AccessToken: resp.GetAccessToken(),
		UserID:      resp.GetUserId(),
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*model.AuthPayload, error) {
	resp, err := r.AuthClient.Login(ctx, &authv1.LoginRequest{Email: email, Password: password})
	if err != nil {
		return nil, translateGRPCError(err)
	}
	// auth-service's Login RPC doesn't return a user_id (it only ever
	// hands back a fresh token); the client can decode the JWT's `sub`
	// claim locally if it needs the ID without a second round trip.
	return &model.AuthPayload{
		AccessToken: resp.GetAccessToken(),
	}, nil
}

// GoogleOAuthCallback is the resolver for the googleOAuthCallback field.
// Thin pass-through to auth-service's GoogleOAuthCallback RPC, same shape
// as Register/Login — see docs/DECISIONS.md for the account-linking rule
// this ultimately triggers on auth-service's side.
func (r *mutationResolver) GoogleOAuthCallback(ctx context.Context, code string) (*model.AuthPayload, error) {
	resp, err := r.AuthClient.GoogleOAuthCallback(ctx, &authv1.GoogleOAuthCallbackRequest{Code: code})
	if err != nil {
		return nil, translateGRPCError(err)
	}
	return &model.AuthPayload{
		AccessToken: resp.GetAccessToken(),
		UserID:      resp.GetUserId(),
	}, nil
}

// CreateSkill is the resolver for the createSkill field. Unauthenticated
// in Phase 1b — there is no role system yet, so anyone can add a skill to
// the taxonomy (see docs/DECISIONS.md).
func (r *mutationResolver) CreateSkill(ctx context.Context, name string, category string) (*model.Skill, error) {
	resp, err := r.SkillsClient.CreateSkill(ctx, &skillsv1.CreateSkillRequest{Name: name, Category: category})
	if err != nil {
		return nil, translateGRPCError(err)
	}
	return toModelSkill(resp.GetSkill()), nil
}

// CreateJob is the resolver for the createJob field. Unauthenticated in
// Phase 1b, same reasoning as CreateSkill.
func (r *mutationResolver) CreateJob(ctx context.Context, title string, description string, requiredSkillIds []string) (*model.Job, error) {
	resp, err := r.JobsClient.CreateJob(ctx, &jobsv1.CreateJobRequest{
		Title:            title,
		Description:      description,
		RequiredSkillIds: requiredSkillIds,
	})
	if err != nil {
		return nil, translateGRPCError(err)
	}
	return toModelJob(resp.GetJob()), nil
}

// UpdateProfile is the resolver for the updateProfile field. Requires an
// authenticated caller (see requireUserID); lazily creates the profile on
// first touch via users-service if none exists yet (see
// docs/DECISIONS.md). displayName/bio are both optional so a caller can
// change just one without clobbering the other with an empty string.
func (r *mutationResolver) UpdateProfile(ctx context.Context, displayName *string, bio *string) (*model.Profile, error) {
	userID, err := requireUserID(ctx)
	if err != nil {
		return nil, err
	}
	resp, err := r.UsersClient.UpdateProfile(ctx, &usersv1.UpdateProfileRequest{
		UserId:      userID,
		DisplayName: displayName,
		Bio:         bio,
	})
	if err != nil {
		return nil, translateGRPCError(err)
	}
	return toModelProfile(resp.GetProfile()), nil
}

// AddUserSkill is the resolver for the addUserSkill field. Requires an
// authenticated caller; skillId is trusted as a valid skills-service ID
// (see users.proto for why users-service can't verify it directly).
func (r *mutationResolver) AddUserSkill(ctx context.Context, skillID string, proficiency string) (bool, error) {
	userID, err := requireUserID(ctx)
	if err != nil {
		return false, err
	}
	if _, err := r.UsersClient.AddUserSkill(ctx, &usersv1.AddUserSkillRequest{
		UserId:      userID,
		SkillId:     skillID,
		Proficiency: proficiency,
	}); err != nil {
		return false, translateGRPCError(err)
	}
	return true, nil
}

// Skills is the resolver for the Profile.skills field. Fetches this
// profile's (skill_id, proficiency) pairs from users-service in one call,
// then leaves resolving each entry's full Skill to UserSkill's own
// `skill` field resolver — see resolveSkills and docs/DECISIONS.md for
// why that's a deliberate N+1 rather than solved here.
func (r *profileResolver) Skills(ctx context.Context, obj *model.Profile) ([]*model.UserSkill, error) {
	resp, err := r.UsersClient.ListUserSkills(ctx, &usersv1.ListUserSkillsRequest{UserId: obj.UserID})
	if err != nil {
		return nil, translateGRPCError(err)
	}
	out := make([]*model.UserSkill, 0, len(resp.GetUserSkills()))
	for _, us := range resp.GetUserSkills() {
		out = append(out, &model.UserSkill{SkillID: us.GetSkillId(), Proficiency: us.GetProficiency()})
	}
	return out, nil
}

// Ping is the resolver for the ping field.
func (r *queryResolver) Ping(ctx context.Context) (string, error) {
	return "pong", nil
}

// GoogleAuthURL is the resolver for the googleAuthUrl field. Thin
// pass-through to auth-service's GetGoogleAuthURL RPC — state is forwarded
// verbatim; auth-service is stateless and never generates or remembers it
// itself (see auth.proto's GetGoogleAuthURLRequest and docs/DECISIONS.md).
func (r *queryResolver) GoogleAuthURL(ctx context.Context, state string) (string, error) {
	resp, err := r.AuthClient.GetGoogleAuthURL(ctx, &authv1.GetGoogleAuthURLRequest{State: state})
	if err != nil {
		return "", translateGRPCError(err)
	}
	return resp.GetAuthUrl(), nil
}

// Skills is the resolver for the Query.skills field. Unauthenticated.
func (r *queryResolver) Skills(ctx context.Context) ([]*model.Skill, error) {
	resp, err := r.SkillsClient.ListSkills(ctx, &skillsv1.ListSkillsRequest{})
	if err != nil {
		return nil, translateGRPCError(err)
	}
	out := make([]*model.Skill, 0, len(resp.GetSkills()))
	for _, sk := range resp.GetSkills() {
		out = append(out, toModelSkill(sk))
	}
	return out, nil
}

// Jobs is the resolver for the Query.jobs field. Unauthenticated.
func (r *queryResolver) Jobs(ctx context.Context) ([]*model.Job, error) {
	resp, err := r.JobsClient.ListJobs(ctx, &jobsv1.ListJobsRequest{})
	if err != nil {
		return nil, translateGRPCError(err)
	}
	out := make([]*model.Job, 0, len(resp.GetJobs()))
	for _, j := range resp.GetJobs() {
		out = append(out, toModelJob(j))
	}
	return out, nil
}

// Job is the resolver for the Query.job field. Unauthenticated. Returns
// nil (not a GraphQL error) when jobs-service reports NotFound, matching
// the schema's nullable return type.
func (r *queryResolver) Job(ctx context.Context, id string) (*model.Job, error) {
	resp, err := r.JobsClient.GetJob(ctx, &jobsv1.GetJobRequest{Id: id})
	if err != nil {
		if status.Code(err) == codes.NotFound {
			return nil, nil
		}
		return nil, translateGRPCError(err)
	}
	return toModelJob(resp.GetJob()), nil
}

// MyProfile is the resolver for the Query.myProfile field. Requires an
// authenticated caller; lazily creates the profile on first touch via
// users-service if none exists yet (see docs/DECISIONS.md).
func (r *queryResolver) MyProfile(ctx context.Context) (*model.Profile, error) {
	userID, err := requireUserID(ctx)
	if err != nil {
		return nil, err
	}
	resp, err := r.UsersClient.GetProfile(ctx, &usersv1.GetProfileRequest{UserId: userID})
	if err != nil {
		return nil, translateGRPCError(err)
	}
	return toModelProfile(resp.GetProfile()), nil
}

// OnNotification is the resolver for the onNotification field (Phase
// 3.5). requireUserID here is defense in depth, not the primary auth
// gate: a WebSocket connection with no valid token is already rejected at
// connection_init time (see cmd/api-gateway/main.go's wsInitFunc), before
// any subscription over that connection can ever be started.
//
// Subscribes to this user's Redis pub/sub channel
// (realtime.UserChannel(userID) — see internal/gateway/realtime, the
// RabbitMQ -> Redis bridge that publishes onto it) and forwards each
// message, decoded from JSON, into the channel gqlgen streams back to the
// client as this field's output. Cleanup — Redis UNSUBSCRIBE via
// Subscription.Close, and closing the output channel — happens in exactly
// one place: the forwarding goroutine's defer, triggered when ctx is
// cancelled (the client disconnects, or gqlgen cancels this specific
// subscription's context on a graphql-ws `stop` message — see
// transport.Websocket's subscribe/stop handling in the gqlgen library).
// This is what makes a dropped WebSocket client release its Redis
// subscription instead of leaking it — verified live via `PUBSUB NUMSUB`
// before/after a client disconnect, see docs/DECISIONS.md.
func (r *subscriptionResolver) OnNotification(ctx context.Context) (<-chan *model.Notification, error) {
	userID, err := requireUserID(ctx)
	if err != nil {
		return nil, err
	}

	sub, ok := r.Realtime.Subscribe(ctx, realtime.UserChannel(userID))
	if !ok {
		return nil, &gqlError{msg: "realtime notifications are unavailable on this instance"}
	}

	out := make(chan *model.Notification)
	go func() {
		defer close(out)
		defer func() { _ = sub.Close() }()
		for {
			select {
			case <-ctx.Done():
				return
			case msg, ok := <-sub.Channel():
				if !ok {
					return
				}
				var notif rabbitmq.RealtimeNotification
				if err := json.Unmarshal([]byte(msg.Payload), &notif); err != nil {
					// Same "log and drop, never crash the consumer" discipline
					// as every other broker-payload decode in this codebase —
					// see internal/gateway/realtime.Bridge.Handler.
					continue
				}
				select {
				case out <- &model.Notification{
					ID:        notif.ID,
					Type:      notif.Type,
					Message:   notif.Message,
					CreatedAt: notif.CreatedAt.UTC().Format(time.RFC3339),
				}:
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return out, nil
}

// Skill is the resolver for the UserSkill.skill field. Same batched path
// as Job.requiredSkills — see resolveSkillsViaLoader.
func (r *userSkillResolver) Skill(ctx context.Context, obj *model.UserSkill) (*model.Skill, error) {
	skills, err := r.resolveSkillsViaLoader(ctx, []string{obj.SkillID})
	if err != nil {
		return nil, err
	}
	if len(skills) == 0 {
		return nil, nil
	}
	return skills[0], nil
}

// Job returns generated.JobResolver implementation.
func (r *Resolver) Job() generated.JobResolver { return &jobResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Profile returns generated.ProfileResolver implementation.
func (r *Resolver) Profile() generated.ProfileResolver { return &profileResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

// UserSkill returns generated.UserSkillResolver implementation.
func (r *Resolver) UserSkill() generated.UserSkillResolver { return &userSkillResolver{r} }

type (
	jobResolver          struct{ *Resolver }
	mutationResolver     struct{ *Resolver }
	profileResolver      struct{ *Resolver }
	queryResolver        struct{ *Resolver }
	subscriptionResolver struct{ *Resolver }
	userSkillResolver    struct{ *Resolver }
)
