apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: skill-bridge
spec:
  selector:
    app: auth-service
  ports:
    - name: grpc
      port: 9001
      targetPort: 9001
    - name: http
      port: 8081
      targetPort: 8081
