// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthPayload struct {
	AccessToken string `json:"accessToken"`
	UserID      string `json:"userId"`
}

type JobMatch struct {
	UserID    string  `json:"userId"`
	Score     float64 `json:"score"`
	MatchedAt string  `json:"matchedAt"`
}

type Mutation struct {
}

type Notification struct {
	ID        string `json:"id"`
	Type      string `json:"type"`
	Message   string `json:"message"`
	CreatedAt string `json:"createdAt"`
}

type Query struct {
}

type Skill struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Category string `json:"category"`
}

type Subscription struct {
}
