// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthPayload struct {
	AccessToken string `json:"accessToken"`
	UserID      string `json:"userId"`
}

type Mutation struct {
}

type Query struct {
}

type Skill struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Category string `json:"category"`
}
