-- +goose Up
-- notifications.notification_log is the one table notification-service
-- (NestJS, backend/notification-service/) owns. It's still a goose
-- migration run the same way every other service's is (`make migrate-up`,
-- or standalone: `goose -dir migrations/notifications -table
-- notifications.goose_db_version postgres "$DATABASE_URL" up`) even though
-- the consuming application code is TypeScript, not Go — goose is a CLI
-- against Postgres, not a Go-specific tool, so this fits the existing
-- per-service migration pattern instead of inventing a second migration
-- mechanism just for the one Node service. See
-- docs/DECISIONS.md's "notification-service's ORM" note for why this
-- table is managed by a handwritten SQL migration + the plain `pg` driver
-- rather than Prisma/TypeORM.
--
-- message_id is the idempotency key: it's the EmailNotification.MessageID
-- generated by auth-service's producer (see
-- internal/platform/rabbitmq/events.go) and carried unchanged through the
-- RabbitMQ message body. notification-service's consumer INSERTs with
-- `ON CONFLICT (message_id) DO NOTHING` and acks either way, so
-- at-least-once redelivery of the exact same message (a consumer restart
-- before the original ack landed, or a manual republish while debugging)
-- never produces a second row — see
-- backend/notification-service/src/rabbitmq/rabbitmq.consumer.ts.
CREATE TABLE IF NOT EXISTS notifications.notification_log (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    message_id  UUID NOT NULL,
    user_id     UUID NOT NULL,
    email       TEXT NOT NULL,
    event_type  TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT notification_log_message_id_key UNIQUE (message_id)
);

CREATE INDEX IF NOT EXISTS idx_notification_log_user_id ON notifications.notification_log (user_id);

-- +goose Down
DROP TABLE IF EXISTS notifications.notification_log;
